[[plugins]]
package = "@netlify/plugin-gatsby"


[build.environment]
  NODE_VERSION = "24.21.0"
  NPM_FLAGS = "--legacy-peer-deps"

[[redirects]]
  from = "/initiatives/offer-plus"
  to = "/initiatives/foundry"
  status = 301

[[redirects]]
  from = "/dashboard/*"
  to = "/dashboard/index.html"
  status = 200

[[redirects]]
  from = "/zoom"
  to = "https://pitt.zoom.us/my/pittcsc"
  status = 200
  force = true

[[redirects]]
  from = "/blog"
  to = "https://pittcsc-blog.netlify.app"
  status = 200
  force = true
