export const officerList = [
  {
    name: "Olivia Wininsky",
    title: "President",
    linkedIn: "https://www.linkedin.com/in/oliviawininsky/",
    email: "onw5@pitt.edu",
    image: "../images/officers/olivia.png",
  },
  {
    name: "Courtney Sheridan",
    title: "Vice President",
    linkedIn: "https://www.linkedin.com/in/courtneyrsheridan/",
    email: "crs173@pitt.edu",
    image: "../images/officers/courtney_image.jpg",
    bio: "Courtney is a sophomore CS major who loves working on exciting problems! As CSC's VP, she helps manage alumni and corporate sponsor relations to bring engaging programs and events to members. Outside of academics, she's involved in Pitt's marching band and enjoys volunteering, which tends to center around mentoring younger students in CS and public service (such as VaccinatePA.org).",
  },
  {
    name: "Sean Steinle",
    title: "Business Manager",
    linkedIn: "https://www.linkedin.com/in/sean-steinle",
    email: "sts137@pitt.edu",
    image: "../images/officers/sgb_headshot.jfif",
  },
  {
    name: "Richie Goulazian",
    title: "Experiential Learning Director",
    linkedIn: "https://www.linkedin.com/in/rgoulazian/",
    email: "rhg13@pitt.edu",
    image: "../images/officers/richie.jpg",
    bio: "Richie is a junior Computer Science major who outside of his regular classwork, enjoys working on personal programming projects. As an officer for CSC, Richie is responsible for experiential learning programs like the student-run hackathon CSC Hacks and the organization of special interest groups with CSC Branches. Richie also enjoys building computers and playing VR games!",
  },

  {
    name: "Dylan Feehan",
    title: "Operations Manager",
    linkedIn: "https://www.linkedin.com/in/dylan-feehan/",
    email: "djf92@pitt.edu",
    image: "../images/officers/dylan.jpg",
    bio: "Dylan is a rising junior majoring in computer science. He loves giving back to the university and helping build the Pitt CS community. Aside from his academic endeavors, he likes to exercise, play piano, and meet new people. Right now, he’s learning C++ to explore lower level programming languages. His favorite piece of advice is to view his CS education as a tool for solving problems that are important to him (shoutout to Ritwik and Mat V for the advice).",
  },
  {
    name: "Jamir Grier",
    title: "Events Coordinator",
    linkedIn: "https://www.linkedin.com/in/jamir-grier-594518182/",
    email: "jlg21@pitt.edu",
    image: "../images/officers/jamir.jpg",
    bio: "Jamir is a sophmore  majoring in Computer Science. His passion is in human-technology interaction, which has led him to look into all sorts of design stratefies and the theory behind systems and design! Outside of academia he is a big fan of video games, anime, music, and comic books. Jamir also plays basketball, lacrosse, and football with friends on nice days, because it's always nice to get out.",
  },

  {
    name: "Alexander Grattan",
    title: "Public Relations Manager",
    linkedIn: "https://www.linkedin.com/in/alexander-grattan/",
    email: "ajg162@pitt.edu",
    image: "../images/officers/Alexander_Grattan_Picture.jpg",
    bio: "Alexander is a Junior Digital Narrative and Interactive Design major with a CS minor. He loves web-dev and making content! He made the website you're reading this bio off of right now. You'll find Alexander in his free time playing/reffing soccer, finding new tunes to code to, exploring Pittsburgh or eating yet another granola bar.",
  },
  {
    name: "Crystal Li",
    title: "Partnership Director",
    linkedIn: "http://linkedin.com/in/itscrystalli",
    email: "crl84@pitt.edu",
    image: "../images/officers/crystal_profile_pic.jpg",
    bio: "Crystal is a junior double majoring in Computer Science and Digital Narrative and Interactive Design with a certificate in Digital Media. Her passion lies in the intersection between technology, user experience, design, and business strategy, which led her to become interested in PM, HCI, and Growth Marketing-related things! Outside of tech stuff, she is a big fan of all forms of storytelling - books, anime, music, and podcasts! She also loves to drink boba and grub on delicious food. 😄",
  },
  {
    name: "Eshan Parmar",
    title: "Officer",
    linkedIn: "https://www.linkedin.com/in/eshan-parmar-878275172/",
    email: "esp27@pitt.edu",
    image: "../images/officers/eshan.jpeg",
    bio: "Eshan is a Senior Computer Science Major with an Econ Minor who loves problem-solving! He enjoys finding ways to connect CS with finance which has led to an interest in FinTech. Outside of school, you'll find Eshan hiking, listening to music, or tossing a frisbee with some friends.",
  },
];
