export const officerList = [
  {
    name: "Jamir Grier",
    title: "President",
    linkedIn: "https://www.linkedin.com/in/~jamir/",
    email: "juhmeer.grear@gmail.com",
    image: "../images/officers_2022/jamir.jpg",
    bio: "Jamir is a rising junior from Washington, DC. He’s known to tinker with gadgets and programs alike, and when he’s not working with tech or planning events, he’s often found to be playing video games or attending conventions. He has interned at Google, the National Institutes of Health, the American Psychological Association, as well as the High School Esports League. He’s open to contact via linked in or email, so feel free to reach out!",
  },
  {
    name: "Robbie Fishel",
    title: "Vice President",
    linkedIn: "https://www.linkedin.com/in/robert-fishel-58ba59193/",
    email: "robbie.fishel6@gmail.com",
    image: "../images/officers_2022/robbie.jpg",
    bio: "Hey guys! My name’s Robbie, I’m this year's VP for CSC and a third-year CS major in the BS+MS program. I’m also a TA for CS 445 and SCI Peer Tutor for several programming classes. I’m originally from Farmington, CT, but my family is from the area and I’ve always considered myself a yinzer. Outside of CS, I'm a massive sports enthusiast (Go Steelers and Pitt sports!!) and play viola in Pitt's Symphony Orchestra. Really excited to continue to help grow CSC and the CS program in general at Pitt this year!",
  },
  {
    name: "Simon Schueller",
    title: "Events Coordinator",
    linkedIn: "https://www.linkedin.com/in/simonsayshello",
    email: "sps67@pitt.edu",
    image: "../images/officers_2022/simon.jpeg",
    bio: "Simon is a third year student pursuing a BS + MS in Computer Science. In his freetime, Simon likes to stay active by playing basketball, golf, and hiking up tall mountains 😎. Simon is passionate about teaching others and is involved with career development events through CSC. Feel free to connect with him on linkedin or shoot an email over.",
  },
  {
    name: "Pratham Patel",
    title: "Project Manager",
    linkedIn: "https://www.linkedin.com/in/patelpratham11/",
    email: "prp48@pitt.edu",
    image: "../images/officers_2022/pratham.jpg",
    bio: "Hey all, my name is Pratham. I'm a recent CS major (originally neuroscience) with a minor in Chemistry. I'm originally from Downingtown, PA so I'm an Eagles fan (go birds!). Aside from CS-y nerd stuff, I love true crime, reading, and photography. Feel free to say hi to me on campus!",
  },
  {
    name: "Abhinav Srinivasan",
    title: "Partnerships Director",
    linkedIn: "https://www.linkedin.com/in/abhisrini/",
    email: "abhisriny@gmail.com",
    image: "../images/officers_2022/abhinav.jpg",
    bio: "Hey guys, this year, I hope to help lead the partnerships the club has with other organizations. As an officer and member of the academic affairs committee in student government, I hope to act and eventually help grow the connection between CSC and the Student government.",
  },
  {
    name: "Minhal Khan",
    title: "Public Relations Manager",
    linkedIn: "https://www.linkedin.com/in/~minhal/",
    email: "mik172@pitt.edu",
    image: "../images/officers_2022/minhal.jpg",
    bio: "Hey everyone! Minhal Khan here. I’m an international student and a rising junior here at Pitt. Although I am a CS major, I’ve recently taken an interest in the dark arts of mathematics and theoretical computer science. I enjoy making things, so you can usually find me drawing, cooking, programming, or making awful music in FL studio.",
  },
  {
    name: "Michael Henry",
    title: "Chief Technology Officer",
    linkedIn: "https://www.linkedin.com/in/michael-lj-henry-1b0803207/",
    email: "mlh184@pitt.edu",
    image: "../images/officers_2022/justin.png",
    bio: "I am computer science major at Pitt. I am a junior and a peer tutor. I enjoy watching sports, reading philosophy, and spending quality time with friends and family. Feel free to reach out to me on linkedIn, email, or in-person.",
  }
];
